name: Pergunta ou Dúvida
description: Tire uma dúvida sobre a instalação ou uso do Nanci
title: "[Dúvida]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Antes de abrir a dúvida, verifique se a sua pergunta já não está respondida no website ou issue existente.

  - type: textarea
    id: question
    attributes:
      label: Qual a sua dúvida?
      description: Seja o mais descritivo possível.
    validations:
      required: true
