// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: companies.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const assignCredentialToCompany = `-- name: AssignCredentialToCompany :execrows
UPDATE companies
SET credential_id = ?1,
    credential_label = (
        SELECT label FROM credentials
        WHERE credentials.id = ?1
    ),
    credential_cert_path = (
        SELECT cert_path FROM credentials
        WHERE credentials.id = ?1
    ),
    environment = (
        SELECT environment FROM credentials
        WHERE credentials.id = ?1
    ),
    updated_at = ?2
WHERE companies.id = ?3
  AND EXISTS (
      SELECT 1 FROM credentials
      WHERE credentials.id = ?1
  )
`

type AssignCredentialToCompanyParams struct {
	CredentialID sql.NullString
	UpdatedAt    string
	CompanyID    string
}

func (q *Queries) AssignCredentialToCompany(ctx context.Context, arg AssignCredentialToCompanyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignCredentialToCompany, arg.CredentialID, arg.UpdatedAt, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCompany = `-- name: CreateCompany :exec
INSERT INTO companies (
    id, cnpj, cnpj_root, name, credential_id, credential_label,
    credential_cert_path, environment, last_nsu, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
`

type CreateCompanyParams struct {
	ID                 string
	Cnpj               string
	CnpjRoot           string
	Name               string
	CredentialID       sql.NullString
	CredentialLabel    sql.NullString
	CredentialCertPath sql.NullString
	Environment        string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) error {
	_, err := q.db.ExecContext(ctx, createCompany,
		arg.ID,
		arg.Cnpj,
		arg.CnpjRoot,
		arg.Name,
		arg.CredentialID,
		arg.CredentialLabel,
		arg.CredentialCertPath,
		arg.Environment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCompanyByCNPJ = `-- name: GetCompanyByCNPJ :one
SELECT id, cnpj, cnpj_root, name, credential_id, credential_label, credential_cert_path, environment, last_nsu, created_at, updated_at FROM companies WHERE cnpj = ? LIMIT 1
`

func (q *Queries) GetCompanyByCNPJ(ctx context.Context, cnpj string) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByCNPJ, cnpj)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Cnpj,
		&i.CnpjRoot,
		&i.Name,
		&i.CredentialID,
		&i.CredentialLabel,
		&i.CredentialCertPath,
		&i.Environment,
		&i.LastNsu,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, cnpj, cnpj_root, name, credential_id, credential_label, credential_cert_path, environment, last_nsu, created_at, updated_at FROM companies ORDER BY name ASC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Cnpj,
			&i.CnpjRoot,
			&i.Name,
			&i.CredentialID,
			&i.CredentialLabel,
			&i.CredentialCertPath,
			&i.Environment,
			&i.LastNsu,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyNSU = `-- name: UpdateCompanyNSU :exec
UPDATE companies
SET last_nsu = ?, updated_at = ?
WHERE id = ?
`

type UpdateCompanyNSUParams struct {
	LastNsu   int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateCompanyNSU(ctx context.Context, arg UpdateCompanyNSUParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyNSU, arg.LastNsu, arg.UpdatedAt, arg.ID)
	return err
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE companies
SET name = ?, environment = ?, updated_at = ?
WHERE id = ?
`

type UpdateCompanyParams struct {
	Name        string
	Environment string
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.db.ExecContext(ctx, updateCompany,
		arg.Name,
		arg.Environment,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
