// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: companies.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const assignCredentialToCompany = `-- name: AssignCredentialToCompany :execrows
UPDATE companies
SET credential_id = ?1,
    credential_label = (
        SELECT label FROM credentials
        WHERE credentials.id = ?1
    ),
    credential_cert_path = (
        SELECT cert_path FROM credentials
        WHERE credentials.id = ?1
    ),
    updated_at = ?2
WHERE companies.id = ?3
  AND EXISTS (
      SELECT 1 FROM credentials
      WHERE credentials.id = ?1
  )
`

type AssignCredentialToCompanyParams struct {
	CredentialID sql.NullString
	UpdatedAt    string
	CompanyID    string
}

func (q *Queries) AssignCredentialToCompany(ctx context.Context, arg AssignCredentialToCompanyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignCredentialToCompany, arg.CredentialID, arg.UpdatedAt, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCompany = `-- name: CreateCompany :exec
INSERT INTO companies (
    id, cnpj, cnpj_root, name, credential_id, credential_label,
    credential_cert_path, environment, sync_start_policy,
    sync_start_date, created_at, updated_at, uf
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCompanyParams struct {
	ID                 string
	Cnpj               string
	CnpjRoot           string
	Name               string
	CredentialID       sql.NullString
	CredentialLabel    sql.NullString
	CredentialCertPath sql.NullString
	Environment        string
	SyncStartPolicy    string
	SyncStartDate      sql.NullString
	CreatedAt          string
	UpdatedAt          string
	Uf                 string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) error {
	_, err := q.db.ExecContext(ctx, createCompany,
		arg.ID,
		arg.Cnpj,
		arg.CnpjRoot,
		arg.Name,
		arg.CredentialID,
		arg.CredentialLabel,
		arg.CredentialCertPath,
		arg.Environment,
		arg.SyncStartPolicy,
		arg.SyncStartDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Uf,
	)
	return err
}

const getCompanyByCNPJ = `-- name: GetCompanyByCNPJ :one
SELECT companies.id, companies.cnpj, companies.cnpj_root, companies.name, companies.credential_id, companies.credential_label, companies.credential_cert_path, companies.environment, companies.sync_start_policy, companies.sync_start_date, companies.created_at, companies.updated_at, companies.uf, company_sync_sources.initial_sync_completed_at AS nfse_initial_sync_completed_at
FROM companies
LEFT JOIN company_sync_sources
    ON company_sync_sources.company_id = companies.id AND company_sync_sources.source = 'nfse'
WHERE companies.cnpj = ? LIMIT 1
`

type GetCompanyByCNPJRow struct {
	Company                    Company
	NfseInitialSyncCompletedAt sql.NullString
}

// The NFS-e initial sync comes from company_sync_sources; it is NULL for a
// company that never finished one.
func (q *Queries) GetCompanyByCNPJ(ctx context.Context, cnpj string) (GetCompanyByCNPJRow, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByCNPJ, cnpj)
	var i GetCompanyByCNPJRow
	err := row.Scan(
		&i.Company.ID,
		&i.Company.Cnpj,
		&i.Company.CnpjRoot,
		&i.Company.Name,
		&i.Company.CredentialID,
		&i.Company.CredentialLabel,
		&i.Company.CredentialCertPath,
		&i.Company.Environment,
		&i.Company.SyncStartPolicy,
		&i.Company.SyncStartDate,
		&i.Company.CreatedAt,
		&i.Company.UpdatedAt,
		&i.Company.Uf,
		&i.NfseInitialSyncCompletedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT companies.id, companies.cnpj, companies.cnpj_root, companies.name, companies.credential_id, companies.credential_label, companies.credential_cert_path, companies.environment, companies.sync_start_policy, companies.sync_start_date, companies.created_at, companies.updated_at, companies.uf, company_sync_sources.initial_sync_completed_at AS nfse_initial_sync_completed_at
FROM companies
LEFT JOIN company_sync_sources
    ON company_sync_sources.company_id = companies.id AND company_sync_sources.source = 'nfse'
ORDER BY companies.name ASC
`

type ListCompaniesRow struct {
	Company                    Company
	NfseInitialSyncCompletedAt sql.NullString
}

// Same NFS-e initial sync join as GetCompanyByCNPJ.
func (q *Queries) ListCompanies(ctx context.Context) ([]ListCompaniesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesRow
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.Company.ID,
			&i.Company.Cnpj,
			&i.Company.CnpjRoot,
			&i.Company.Name,
			&i.Company.CredentialID,
			&i.Company.CredentialLabel,
			&i.Company.CredentialCertPath,
			&i.Company.Environment,
			&i.Company.SyncStartPolicy,
			&i.Company.SyncStartDate,
			&i.Company.CreatedAt,
			&i.Company.UpdatedAt,
			&i.Company.Uf,
			&i.NfseInitialSyncCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE companies
SET name = ?,
    environment = ?,
    sync_start_policy = ?,
    sync_start_date = ?,
    uf = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCompanyParams struct {
	Name            string
	Environment     string
	SyncStartPolicy string
	SyncStartDate   sql.NullString
	Uf              string
	UpdatedAt       string
	ID              string
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.db.ExecContext(ctx, updateCompany,
		arg.Name,
		arg.Environment,
		arg.SyncStartPolicy,
		arg.SyncStartDate,
		arg.Uf,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
