// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credentials.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (
    id, label, cert_path, environment, owner_cnpj, owner_cnpj_root, 
    fingerprint_sha256, subject_name, not_before, not_after, inspected_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCredentialParams struct {
	ID                string
	Label             string
	CertPath          string
	Environment       string
	OwnerCnpj         string
	OwnerCnpjRoot     string
	FingerprintSha256 string
	SubjectName       string
	NotBefore         sql.NullString
	NotAfter          sql.NullString
	InspectedAt       sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createCredential,
		arg.ID,
		arg.Label,
		arg.CertPath,
		arg.Environment,
		arg.OwnerCnpj,
		arg.OwnerCnpjRoot,
		arg.FingerprintSha256,
		arg.SubjectName,
		arg.NotBefore,
		arg.NotAfter,
		arg.InspectedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, id)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, label, cert_path, environment, owner_cnpj, owner_cnpj_root, fingerprint_sha256, subject_name, not_before, not_after, inspected_at, created_at, updated_at FROM credentials WHERE id = ? LIMIT 1
`

func (q *Queries) GetCredential(ctx context.Context, id string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.CertPath,
		&i.Environment,
		&i.OwnerCnpj,
		&i.OwnerCnpjRoot,
		&i.FingerprintSha256,
		&i.SubjectName,
		&i.NotBefore,
		&i.NotAfter,
		&i.InspectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, label, cert_path, environment, owner_cnpj, owner_cnpj_root, fingerprint_sha256, subject_name, not_before, not_after, inspected_at, created_at, updated_at FROM credentials ORDER BY label ASC
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CertPath,
			&i.Environment,
			&i.OwnerCnpj,
			&i.OwnerCnpjRoot,
			&i.FingerprintSha256,
			&i.SubjectName,
			&i.NotBefore,
			&i.NotAfter,
			&i.InspectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials
SET
    label = ?,
    cert_path = ?,
    environment = ?,
    owner_cnpj = ?,
    owner_cnpj_root = ?,
    fingerprint_sha256 = ?,
    subject_name = ?,
    not_before = ?,
    not_after = ?,
    inspected_at = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCredentialParams struct {
	Label             string
	CertPath          string
	Environment       string
	OwnerCnpj         string
	OwnerCnpjRoot     string
	FingerprintSha256 string
	SubjectName       string
	NotBefore         sql.NullString
	NotAfter          sql.NullString
	InspectedAt       sql.NullString
	UpdatedAt         string
	ID                string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateCredential,
		arg.Label,
		arg.CertPath,
		arg.Environment,
		arg.OwnerCnpj,
		arg.OwnerCnpjRoot,
		arg.FingerprintSha256,
		arg.SubjectName,
		arg.NotBefore,
		arg.NotAfter,
		arg.InspectedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
