// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cte.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const getCTeDocumentByChave = `-- name: GetCTeDocumentByChave :one
SELECT id, chave_acesso, tp_amb, modelo, tipo_documento, serie, numero, cfop, nat_op, issue_date, competence, authorized_at, protocolo, tp_cte, tp_serv, modal, mun_ini_codigo, mun_ini_nome, uf_ini, mun_fim_codigo, mun_fim_nome, uf_fim, emitente_cnpj, emitente_name, emitente_ie, emitente_uf, remetente_cnpj, remetente_name, destinatario_cnpj, destinatario_name, expedidor_cnpj, expedidor_name, recebedor_cnpj, recebedor_name, tomador_indicador, tomador_cnpj, tomador_name, tomador_ie, tomador_uf, autorizados_cnpj, nfe_chaves, total_value, receivable_value, icms_value, tot_trib_value, carga_value, produto_predominante, situacao, layout_version, raw_hash, parse_warnings, created_at, updated_at FROM cte_documents WHERE chave_acesso = ? LIMIT 1
`

func (q *Queries) GetCTeDocumentByChave(ctx context.Context, chaveAcesso string) (CteDocument, error) {
	row := q.db.QueryRowContext(ctx, getCTeDocumentByChave, chaveAcesso)
	var i CteDocument
	err := row.Scan(
		&i.ID,
		&i.ChaveAcesso,
		&i.TpAmb,
		&i.Modelo,
		&i.TipoDocumento,
		&i.Serie,
		&i.Numero,
		&i.Cfop,
		&i.NatOp,
		&i.IssueDate,
		&i.Competence,
		&i.AuthorizedAt,
		&i.Protocolo,
		&i.TpCte,
		&i.TpServ,
		&i.Modal,
		&i.MunIniCodigo,
		&i.MunIniNome,
		&i.UfIni,
		&i.MunFimCodigo,
		&i.MunFimNome,
		&i.UfFim,
		&i.EmitenteCnpj,
		&i.EmitenteName,
		&i.EmitenteIe,
		&i.EmitenteUf,
		&i.RemetenteCnpj,
		&i.RemetenteName,
		&i.DestinatarioCnpj,
		&i.DestinatarioName,
		&i.ExpedidorCnpj,
		&i.ExpedidorName,
		&i.RecebedorCnpj,
		&i.RecebedorName,
		&i.TomadorIndicador,
		&i.TomadorCnpj,
		&i.TomadorName,
		&i.TomadorIe,
		&i.TomadorUf,
		&i.AutorizadosCnpj,
		&i.NfeChaves,
		&i.TotalValue,
		&i.ReceivableValue,
		&i.IcmsValue,
		&i.TotTribValue,
		&i.CargaValue,
		&i.ProdutoPredominante,
		&i.Situacao,
		&i.LayoutVersion,
		&i.RawHash,
		&i.ParseWarnings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasCTeEvent = `-- name: HasCTeEvent :one
SELECT COUNT(*) FROM cte_events WHERE chave_acesso = ? AND tp_evento = ? AND n_seq_evento = ?
`

type HasCTeEventParams struct {
	ChaveAcesso string
	TpEvento    string
	NSeqEvento  int64
}

func (q *Queries) HasCTeEvent(ctx context.Context, arg HasCTeEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCTeEvent, arg.ChaveAcesso, arg.TpEvento, arg.NSeqEvento)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasCompanyCTeDocument = `-- name: HasCompanyCTeDocument :one
SELECT COUNT(*) FROM company_cte_documents cd
INNER JOIN cte_documents d ON d.id = cd.cte_document_id
WHERE cd.company_id = ? AND d.chave_acesso = ?
`

type HasCompanyCTeDocumentParams struct {
	CompanyID   string
	ChaveAcesso string
}

func (q *Queries) HasCompanyCTeDocument(ctx context.Context, arg HasCompanyCTeDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCompanyCTeDocument, arg.CompanyID, arg.ChaveAcesso)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const linkCTeEventsToDocument = `-- name: LinkCTeEventsToDocument :exec
UPDATE cte_events SET cte_document_id = ? WHERE chave_acesso = ? AND cte_document_id IS NULL
`

type LinkCTeEventsToDocumentParams struct {
	CteDocumentID sql.NullString
	ChaveAcesso   string
}

func (q *Queries) LinkCTeEventsToDocument(ctx context.Context, arg LinkCTeEventsToDocumentParams) error {
	_, err := q.db.ExecContext(ctx, linkCTeEventsToDocument, arg.CteDocumentID, arg.ChaveAcesso)
	return err
}

const listCTeEventsByChave = `-- name: ListCTeEventsByChave :many
SELECT id, cte_document_id, chave_acesso, tp_amb, c_orgao, tp_evento, type, n_seq_evento, event_at, registered_at, registered, c_stat, x_motivo, protocolo, autor_cnpj, description, justificativa, observacao, correcao, condicao_uso, raw_hash, parse_warnings, created_at, updated_at FROM cte_events
WHERE chave_acesso = ?
ORDER BY COALESCE(registered_at, event_at, created_at), tp_evento, n_seq_evento
`

func (q *Queries) ListCTeEventsByChave(ctx context.Context, chaveAcesso string) ([]CteEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCTeEventsByChave, chaveAcesso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CteEvent
	for rows.Next() {
		var i CteEvent
		if err := rows.Scan(
			&i.ID,
			&i.CteDocumentID,
			&i.ChaveAcesso,
			&i.TpAmb,
			&i.COrgao,
			&i.TpEvento,
			&i.Type,
			&i.NSeqEvento,
			&i.EventAt,
			&i.RegisteredAt,
			&i.Registered,
			&i.CStat,
			&i.XMotivo,
			&i.Protocolo,
			&i.AutorCnpj,
			&i.Description,
			&i.Justificativa,
			&i.Observacao,
			&i.Correcao,
			&i.CondicaoUso,
			&i.RawHash,
			&i.ParseWarnings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCTeExported = `-- name: MarkCTeExported :exec
INSERT INTO company_cte_export_marks (company_id, cte_document_id, export_kind, exported_hash, exported_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(company_id, cte_document_id, export_kind) DO UPDATE SET
    exported_hash = excluded.exported_hash,
    exported_at = excluded.exported_at
`

type MarkCTeExportedParams struct {
	CompanyID     string
	CteDocumentID string
	ExportKind    string
	ExportedHash  string
	ExportedAt    string
}

func (q *Queries) MarkCTeExported(ctx context.Context, arg MarkCTeExportedParams) error {
	_, err := q.db.ExecContext(ctx, markCTeExported,
		arg.CompanyID,
		arg.CteDocumentID,
		arg.ExportKind,
		arg.ExportedHash,
		arg.ExportedAt,
	)
	return err
}

const updateCTeSituacao = `-- name: UpdateCTeSituacao :exec
UPDATE cte_documents SET situacao = ?, updated_at = ? WHERE chave_acesso = ?
`

type UpdateCTeSituacaoParams struct {
	Situacao    string
	UpdatedAt   string
	ChaveAcesso string
}

func (q *Queries) UpdateCTeSituacao(ctx context.Context, arg UpdateCTeSituacaoParams) error {
	_, err := q.db.ExecContext(ctx, updateCTeSituacao, arg.Situacao, arg.UpdatedAt, arg.ChaveAcesso)
	return err
}

const upsertCTeDocument = `-- name: UpsertCTeDocument :one
INSERT INTO cte_documents (
    id, chave_acesso, tp_amb, modelo, tipo_documento, serie, numero, cfop, nat_op,
    issue_date, competence, authorized_at, protocolo, tp_cte, tp_serv, modal,
    mun_ini_codigo, mun_ini_nome, uf_ini, mun_fim_codigo, mun_fim_nome, uf_fim,
    emitente_cnpj, emitente_name, emitente_ie, emitente_uf,
    remetente_cnpj, remetente_name, destinatario_cnpj, destinatario_name,
    expedidor_cnpj, expedidor_name, recebedor_cnpj, recebedor_name,
    tomador_indicador, tomador_cnpj, tomador_name, tomador_ie, tomador_uf,
    autorizados_cnpj, nfe_chaves,
    total_value, receivable_value, icms_value, tot_trib_value, carga_value, produto_predominante,
    situacao, layout_version, raw_hash, parse_warnings, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(chave_acesso) DO UPDATE SET
    tp_amb = excluded.tp_amb,
    modelo = excluded.modelo,
    tipo_documento = excluded.tipo_documento,
    serie = excluded.serie,
    numero = excluded.numero,
    cfop = excluded.cfop,
    nat_op = excluded.nat_op,
    issue_date = excluded.issue_date,
    competence = excluded.competence,
    authorized_at = excluded.authorized_at,
    protocolo = excluded.protocolo,
    tp_cte = excluded.tp_cte,
    tp_serv = excluded.tp_serv,
    modal = excluded.modal,
    mun_ini_codigo = excluded.mun_ini_codigo,
    mun_ini_nome = excluded.mun_ini_nome,
    uf_ini = excluded.uf_ini,
    mun_fim_codigo = excluded.mun_fim_codigo,
    mun_fim_nome = excluded.mun_fim_nome,
    uf_fim = excluded.uf_fim,
    emitente_cnpj = excluded.emitente_cnpj,
    emitente_name = excluded.emitente_name,
    emitente_ie = excluded.emitente_ie,
    emitente_uf = excluded.emitente_uf,
    remetente_cnpj = excluded.remetente_cnpj,
    remetente_name = excluded.remetente_name,
    destinatario_cnpj = excluded.destinatario_cnpj,
    destinatario_name = excluded.destinatario_name,
    expedidor_cnpj = excluded.expedidor_cnpj,
    expedidor_name = excluded.expedidor_name,
    recebedor_cnpj = excluded.recebedor_cnpj,
    recebedor_name = excluded.recebedor_name,
    tomador_indicador = excluded.tomador_indicador,
    tomador_cnpj = excluded.tomador_cnpj,
    tomador_name = excluded.tomador_name,
    tomador_ie = excluded.tomador_ie,
    tomador_uf = excluded.tomador_uf,
    autorizados_cnpj = excluded.autorizados_cnpj,
    nfe_chaves = excluded.nfe_chaves,
    total_value = excluded.total_value,
    receivable_value = excluded.receivable_value,
    icms_value = excluded.icms_value,
    tot_trib_value = excluded.tot_trib_value,
    carga_value = excluded.carga_value,
    produto_predominante = excluded.produto_predominante,
    situacao = excluded.situacao,
    layout_version = excluded.layout_version,
    raw_hash = excluded.raw_hash,
    parse_warnings = excluded.parse_warnings,
    updated_at = excluded.updated_at
RETURNING id
`

type UpsertCTeDocumentParams struct {
	ID                  string
	ChaveAcesso         string
	TpAmb               string
	Modelo              string
	TipoDocumento       string
	Serie               string
	Numero              string
	Cfop                string
	NatOp               string
	IssueDate           string
	Competence          string
	AuthorizedAt        sql.NullString
	Protocolo           string
	TpCte               string
	TpServ              string
	Modal               string
	MunIniCodigo        string
	MunIniNome          string
	UfIni               string
	MunFimCodigo        string
	MunFimNome          string
	UfFim               string
	EmitenteCnpj        string
	EmitenteName        string
	EmitenteIe          string
	EmitenteUf          string
	RemetenteCnpj       string
	RemetenteName       string
	DestinatarioCnpj    string
	DestinatarioName    string
	ExpedidorCnpj       string
	ExpedidorName       string
	RecebedorCnpj       string
	RecebedorName       string
	TomadorIndicador    string
	TomadorCnpj         string
	TomadorName         string
	TomadorIe           string
	TomadorUf           string
	AutorizadosCnpj     string
	NfeChaves           string
	TotalValue          int64
	ReceivableValue     int64
	IcmsValue           int64
	TotTribValue        int64
	CargaValue          int64
	ProdutoPredominante string
	Situacao            string
	LayoutVersion       string
	RawHash             string
	ParseWarnings       sql.NullString
	CreatedAt           string
	UpdatedAt           string
}

func (q *Queries) UpsertCTeDocument(ctx context.Context, arg UpsertCTeDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertCTeDocument,
		arg.ID,
		arg.ChaveAcesso,
		arg.TpAmb,
		arg.Modelo,
		arg.TipoDocumento,
		arg.Serie,
		arg.Numero,
		arg.Cfop,
		arg.NatOp,
		arg.IssueDate,
		arg.Competence,
		arg.AuthorizedAt,
		arg.Protocolo,
		arg.TpCte,
		arg.TpServ,
		arg.Modal,
		arg.MunIniCodigo,
		arg.MunIniNome,
		arg.UfIni,
		arg.MunFimCodigo,
		arg.MunFimNome,
		arg.UfFim,
		arg.EmitenteCnpj,
		arg.EmitenteName,
		arg.EmitenteIe,
		arg.EmitenteUf,
		arg.RemetenteCnpj,
		arg.RemetenteName,
		arg.DestinatarioCnpj,
		arg.DestinatarioName,
		arg.ExpedidorCnpj,
		arg.ExpedidorName,
		arg.RecebedorCnpj,
		arg.RecebedorName,
		arg.TomadorIndicador,
		arg.TomadorCnpj,
		arg.TomadorName,
		arg.TomadorIe,
		arg.TomadorUf,
		arg.AutorizadosCnpj,
		arg.NfeChaves,
		arg.TotalValue,
		arg.ReceivableValue,
		arg.IcmsValue,
		arg.TotTribValue,
		arg.CargaValue,
		arg.ProdutoPredominante,
		arg.Situacao,
		arg.LayoutVersion,
		arg.RawHash,
		arg.ParseWarnings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertCTeEvent = `-- name: UpsertCTeEvent :exec
INSERT INTO cte_events (
    id, cte_document_id, chave_acesso, tp_amb, c_orgao, tp_evento, type, n_seq_evento, event_at, registered_at,
    registered, c_stat, x_motivo, protocolo, autor_cnpj, description, justificativa, observacao, correcao,
    condicao_uso, raw_hash, parse_warnings, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chave_acesso, tp_evento, n_seq_evento) DO UPDATE SET
    cte_document_id = COALESCE(cte_events.cte_document_id, excluded.cte_document_id),
    tp_amb = excluded.tp_amb,
    c_orgao = excluded.c_orgao,
    type = excluded.type,
    event_at = excluded.event_at,
    registered_at = excluded.registered_at,
    registered = excluded.registered,
    c_stat = excluded.c_stat,
    x_motivo = excluded.x_motivo,
    protocolo = excluded.protocolo,
    autor_cnpj = excluded.autor_cnpj,
    description = excluded.description,
    justificativa = excluded.justificativa,
    observacao = excluded.observacao,
    correcao = excluded.correcao,
    condicao_uso = excluded.condicao_uso,
    raw_hash = excluded.raw_hash,
    parse_warnings = excluded.parse_warnings,
    updated_at = excluded.updated_at
`

type UpsertCTeEventParams struct {
	ID            string
	CteDocumentID sql.NullString
	ChaveAcesso   string
	TpAmb         string
	COrgao        string
	TpEvento      string
	Type          string
	NSeqEvento    int64
	EventAt       sql.NullString
	RegisteredAt  sql.NullString
	Registered    int64
	CStat         string
	XMotivo       string
	Protocolo     string
	AutorCnpj     string
	Description   string
	Justificativa string
	Observacao    string
	Correcao      string
	CondicaoUso   string
	RawHash       string
	ParseWarnings sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

// Keeps the row id, created_at and the document link.
func (q *Queries) UpsertCTeEvent(ctx context.Context, arg UpsertCTeEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertCTeEvent,
		arg.ID,
		arg.CteDocumentID,
		arg.ChaveAcesso,
		arg.TpAmb,
		arg.COrgao,
		arg.TpEvento,
		arg.Type,
		arg.NSeqEvento,
		arg.EventAt,
		arg.RegisteredAt,
		arg.Registered,
		arg.CStat,
		arg.XMotivo,
		arg.Protocolo,
		arg.AutorCnpj,
		arg.Description,
		arg.Justificativa,
		arg.Observacao,
		arg.Correcao,
		arg.CondicaoUso,
		arg.RawHash,
		arg.ParseWarnings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCompanyCTeDocument = `-- name: UpsertCompanyCTeDocument :exec
INSERT INTO company_cte_documents (
    relation_id, company_id, cte_document_id, company_role, papeis, visibility_reason,
    first_seen_nsu, last_seen_nsu, first_synced_at, last_synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, cte_document_id) DO UPDATE SET
    company_role = excluded.company_role,
    papeis = excluded.papeis,
    visibility_reason = excluded.visibility_reason,
    first_seen_nsu = CASE
        WHEN company_cte_documents.first_seen_nsu IS NULL THEN excluded.first_seen_nsu
        WHEN excluded.first_seen_nsu IS NULL THEN company_cte_documents.first_seen_nsu
        ELSE MIN(company_cte_documents.first_seen_nsu, excluded.first_seen_nsu)
    END,
    last_seen_nsu = CASE
        WHEN company_cte_documents.last_seen_nsu IS NULL THEN excluded.last_seen_nsu
        WHEN excluded.last_seen_nsu IS NULL THEN company_cte_documents.last_seen_nsu
        ELSE MAX(company_cte_documents.last_seen_nsu, excluded.last_seen_nsu)
    END,
    last_synced_at = excluded.last_synced_at
`

type UpsertCompanyCTeDocumentParams struct {
	RelationID       string
	CompanyID        string
	CteDocumentID    string
	CompanyRole      string
	Papeis           string
	VisibilityReason string
	FirstSeenNsu     sql.NullInt64
	LastSeenNsu      sql.NullInt64
	FirstSyncedAt    string
	LastSyncedAt     string
}

func (q *Queries) UpsertCompanyCTeDocument(ctx context.Context, arg UpsertCompanyCTeDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompanyCTeDocument,
		arg.RelationID,
		arg.CompanyID,
		arg.CteDocumentID,
		arg.CompanyRole,
		arg.Papeis,
		arg.VisibilityReason,
		arg.FirstSeenNsu,
		arg.LastSeenNsu,
		arg.FirstSyncedAt,
		arg.LastSyncedAt,
	)
	return err
}
