// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlgen

import (
	"database/sql"
)

type Company struct {
	ID                 string
	Cnpj               string
	CnpjRoot           string
	Name               string
	CredentialID       sql.NullString
	CredentialLabel    sql.NullString
	CredentialCertPath sql.NullString
	Environment        string
	LastNsu            int64
	CreatedAt          string
	UpdatedAt          string
}

type CompanyDocument struct {
	RelationID        string
	CompanyID         string
	DocumentID        string
	CompanyRole       string
	VisibilityReason  string
	FirstSeenNsu      int64
	LastSeenNsu       int64
	FirstSeenNsuValid int64
	LastSeenNsuValid  int64
	FirstSyncedAt     string
	LastSyncedAt      string
}

type Credential struct {
	ID                string
	Label             string
	CertPath          string
	Environment       string
	OwnerCnpj         string
	OwnerCnpjRoot     string
	FingerprintSha256 string
	SubjectName       string
	NotBefore         sql.NullString
	NotAfter          sql.NullString
	InspectedAt       sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type Document struct {
	ID                 string
	ChaveAcesso        string
	IssueDate          string
	Competence         string
	PrestadorCnpj      string
	PrestadorName      string
	TomadorCnpj        string
	TomadorName        string
	IntermediarioCnpj  string
	IntermediarioName  string
	ServiceValue       int64
	IssValue           int64
	IrrfValue          int64
	InssValue          int64
	PisValue           int64
	CofinsValue        int64
	CsllValue          int64
	TotalRetentions    int64
	Status             string
	LayoutVersion      string
	XmlPath            string
	RawHash            string
	ParseWarnings      sql.NullString
	NfseNumber         string
	ServiceDescription string
	CreatedAt          string
	UpdatedAt          string
}

type Event struct {
	ID                     string
	DocumentID             sql.NullString
	ChaveAcesso            string
	Type                   string
	EventAt                sql.NullString
	EventAtValid           int64
	ReplacementChaveAcesso string
	Description            string
	RawXmlPath             string
	RawHash                string
	ParseWarnings          sql.NullString
	CreatedAt              string
}

type SyncRun struct {
	ID                string
	CompanyID         string
	CredentialID      string
	CredentialCnpj    string
	ConsultationCnpj  string
	ConsultationBasis string
	StartedAt         string
	FinishedAt        sql.NullString
	FromNsu           int64
	ToNsu             int64
	DocumentsFound    int64
	ErrorsCount       int64
	Status            string
}
