// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nfe.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const getNFeDocumentByChave = `-- name: GetNFeDocumentByChave :one
SELECT id, chave_acesso, modelo, serie, numero, issue_date, competence, authorized_at, protocolo, emitente_cnpj, emitente_name, emitente_ie, emitente_uf, destinatario_cnpj, destinatario_name, transportador_cnpj, autorizados_cnpj, tp_nf, fin_nfe, nat_op, total_value, icms_value, ipi_value, situacao, completeness, layout_version, raw_hash, resumo_raw_hash, parse_warnings, created_at, updated_at, tp_amb FROM nfe_documents WHERE chave_acesso = ? LIMIT 1
`

func (q *Queries) GetNFeDocumentByChave(ctx context.Context, chaveAcesso string) (NfeDocument, error) {
	row := q.db.QueryRowContext(ctx, getNFeDocumentByChave, chaveAcesso)
	var i NfeDocument
	err := row.Scan(
		&i.ID,
		&i.ChaveAcesso,
		&i.Modelo,
		&i.Serie,
		&i.Numero,
		&i.IssueDate,
		&i.Competence,
		&i.AuthorizedAt,
		&i.Protocolo,
		&i.EmitenteCnpj,
		&i.EmitenteName,
		&i.EmitenteIe,
		&i.EmitenteUf,
		&i.DestinatarioCnpj,
		&i.DestinatarioName,
		&i.TransportadorCnpj,
		&i.AutorizadosCnpj,
		&i.TpNf,
		&i.FinNfe,
		&i.NatOp,
		&i.TotalValue,
		&i.IcmsValue,
		&i.IpiValue,
		&i.Situacao,
		&i.Completeness,
		&i.LayoutVersion,
		&i.RawHash,
		&i.ResumoRawHash,
		&i.ParseWarnings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TpAmb,
	)
	return i, err
}

const hasCompanyNFeDocument = `-- name: HasCompanyNFeDocument :one
SELECT COUNT(*) FROM company_nfe_documents cd
INNER JOIN nfe_documents d ON d.id = cd.nfe_document_id
WHERE cd.company_id = ? AND d.chave_acesso = ?
`

type HasCompanyNFeDocumentParams struct {
	CompanyID   string
	ChaveAcesso string
}

func (q *Queries) HasCompanyNFeDocument(ctx context.Context, arg HasCompanyNFeDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasCompanyNFeDocument, arg.CompanyID, arg.ChaveAcesso)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasNFeEvent = `-- name: HasNFeEvent :one
SELECT COUNT(*) FROM nfe_events WHERE chave_acesso = ? AND tp_evento = ? AND n_seq_evento = ?
`

type HasNFeEventParams struct {
	ChaveAcesso string
	TpEvento    string
	NSeqEvento  int64
}

func (q *Queries) HasNFeEvent(ctx context.Context, arg HasNFeEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasNFeEvent, arg.ChaveAcesso, arg.TpEvento, arg.NSeqEvento)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNFeManifestacao = `-- name: InsertNFeManifestacao :exec
INSERT INTO nfe_manifestacoes (
    id, company_id, chave_acesso, tp_evento, n_seq_evento, justificativa, id_lote,
    status, c_stat, x_motivo, protocolo, registered_at, request_raw_hash, response_raw_hash, created_at,
    tp_amb
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNFeManifestacaoParams struct {
	ID              string
	CompanyID       string
	ChaveAcesso     string
	TpEvento        string
	NSeqEvento      int64
	Justificativa   string
	IDLote          string
	Status          string
	CStat           string
	XMotivo         string
	Protocolo       string
	RegisteredAt    sql.NullString
	RequestRawHash  sql.NullString
	ResponseRawHash sql.NullString
	CreatedAt       string
	TpAmb           string
}

func (q *Queries) InsertNFeManifestacao(ctx context.Context, arg InsertNFeManifestacaoParams) error {
	_, err := q.db.ExecContext(ctx, insertNFeManifestacao,
		arg.ID,
		arg.CompanyID,
		arg.ChaveAcesso,
		arg.TpEvento,
		arg.NSeqEvento,
		arg.Justificativa,
		arg.IDLote,
		arg.Status,
		arg.CStat,
		arg.XMotivo,
		arg.Protocolo,
		arg.RegisteredAt,
		arg.RequestRawHash,
		arg.ResponseRawHash,
		arg.CreatedAt,
		arg.TpAmb,
	)
	return err
}

const linkNFeEventsToDocument = `-- name: LinkNFeEventsToDocument :exec
UPDATE nfe_events SET nfe_document_id = ? WHERE chave_acesso = ? AND nfe_document_id IS NULL
`

type LinkNFeEventsToDocumentParams struct {
	NfeDocumentID sql.NullString
	ChaveAcesso   string
}

func (q *Queries) LinkNFeEventsToDocument(ctx context.Context, arg LinkNFeEventsToDocumentParams) error {
	_, err := q.db.ExecContext(ctx, linkNFeEventsToDocument, arg.NfeDocumentID, arg.ChaveAcesso)
	return err
}

const listCompanyNFeRelationsByChave = `-- name: ListCompanyNFeRelationsByChave :many
SELECT cd.relation_id, c.cnpj FROM company_nfe_documents cd
INNER JOIN nfe_documents d ON d.id = cd.nfe_document_id
INNER JOIN companies c ON c.id = cd.company_id
WHERE d.chave_acesso = ?
`

type ListCompanyNFeRelationsByChaveRow struct {
	RelationID string
	Cnpj       string
}

func (q *Queries) ListCompanyNFeRelationsByChave(ctx context.Context, chaveAcesso string) ([]ListCompanyNFeRelationsByChaveRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyNFeRelationsByChave, chaveAcesso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyNFeRelationsByChaveRow
	for rows.Next() {
		var i ListCompanyNFeRelationsByChaveRow
		if err := rows.Scan(&i.RelationID, &i.Cnpj); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNFeEventsByChave = `-- name: ListNFeEventsByChave :many
SELECT id, nfe_document_id, chave_acesso, tp_evento, type, n_seq_evento, event_at, registered_at, registered, c_stat, x_motivo, protocolo, autor_cnpj, description, justificativa, correcao, completeness, sent_by_nanci, raw_hash, parse_warnings, created_at, updated_at, tp_amb FROM nfe_events
WHERE chave_acesso = ?
ORDER BY COALESCE(registered_at, event_at, created_at), tp_evento, n_seq_evento
`

func (q *Queries) ListNFeEventsByChave(ctx context.Context, chaveAcesso string) ([]NfeEvent, error) {
	rows, err := q.db.QueryContext(ctx, listNFeEventsByChave, chaveAcesso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NfeEvent
	for rows.Next() {
		var i NfeEvent
		if err := rows.Scan(
			&i.ID,
			&i.NfeDocumentID,
			&i.ChaveAcesso,
			&i.TpEvento,
			&i.Type,
			&i.NSeqEvento,
			&i.EventAt,
			&i.RegisteredAt,
			&i.Registered,
			&i.CStat,
			&i.XMotivo,
			&i.Protocolo,
			&i.AutorCnpj,
			&i.Description,
			&i.Justificativa,
			&i.Correcao,
			&i.Completeness,
			&i.SentByNanci,
			&i.RawHash,
			&i.ParseWarnings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TpAmb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNFeExported = `-- name: MarkNFeExported :exec
INSERT INTO company_nfe_export_marks (company_id, nfe_document_id, export_kind, exported_hash, exported_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(company_id, nfe_document_id, export_kind) DO UPDATE SET
    exported_hash = excluded.exported_hash,
    exported_at = excluded.exported_at
`

type MarkNFeExportedParams struct {
	CompanyID     string
	NfeDocumentID string
	ExportKind    string
	ExportedHash  string
	ExportedAt    string
}

func (q *Queries) MarkNFeExported(ctx context.Context, arg MarkNFeExportedParams) error {
	_, err := q.db.ExecContext(ctx, markNFeExported,
		arg.CompanyID,
		arg.NfeDocumentID,
		arg.ExportKind,
		arg.ExportedHash,
		arg.ExportedAt,
	)
	return err
}

const updateCompanyNFeManifestacao = `-- name: UpdateCompanyNFeManifestacao :exec
UPDATE company_nfe_documents SET manifestacao = ?, manifestacao_at = ? WHERE relation_id = ?
`

type UpdateCompanyNFeManifestacaoParams struct {
	Manifestacao   string
	ManifestacaoAt sql.NullString
	RelationID     string
}

func (q *Queries) UpdateCompanyNFeManifestacao(ctx context.Context, arg UpdateCompanyNFeManifestacaoParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyNFeManifestacao, arg.Manifestacao, arg.ManifestacaoAt, arg.RelationID)
	return err
}

const updateNFeSituacao = `-- name: UpdateNFeSituacao :exec
UPDATE nfe_documents SET situacao = ?, updated_at = ? WHERE chave_acesso = ?
`

type UpdateNFeSituacaoParams struct {
	Situacao    string
	UpdatedAt   string
	ChaveAcesso string
}

func (q *Queries) UpdateNFeSituacao(ctx context.Context, arg UpdateNFeSituacaoParams) error {
	_, err := q.db.ExecContext(ctx, updateNFeSituacao, arg.Situacao, arg.UpdatedAt, arg.ChaveAcesso)
	return err
}

const upsertCompanyNFeDocument = `-- name: UpsertCompanyNFeDocument :exec
INSERT INTO company_nfe_documents (
    relation_id, company_id, nfe_document_id, company_role, visibility_reason,
    first_seen_nsu, last_seen_nsu, first_synced_at, last_synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, nfe_document_id) DO UPDATE SET
    company_role = excluded.company_role,
    visibility_reason = excluded.visibility_reason,
    first_seen_nsu = CASE
        WHEN company_nfe_documents.first_seen_nsu IS NULL THEN excluded.first_seen_nsu
        WHEN excluded.first_seen_nsu IS NULL THEN company_nfe_documents.first_seen_nsu
        ELSE MIN(company_nfe_documents.first_seen_nsu, excluded.first_seen_nsu)
    END,
    last_seen_nsu = CASE
        WHEN company_nfe_documents.last_seen_nsu IS NULL THEN excluded.last_seen_nsu
        WHEN excluded.last_seen_nsu IS NULL THEN company_nfe_documents.last_seen_nsu
        ELSE MAX(company_nfe_documents.last_seen_nsu, excluded.last_seen_nsu)
    END,
    last_synced_at = excluded.last_synced_at
`

type UpsertCompanyNFeDocumentParams struct {
	RelationID       string
	CompanyID        string
	NfeDocumentID    string
	CompanyRole      string
	VisibilityReason string
	FirstSeenNsu     sql.NullInt64
	LastSeenNsu      sql.NullInt64
	FirstSyncedAt    string
	LastSyncedAt     string
}

func (q *Queries) UpsertCompanyNFeDocument(ctx context.Context, arg UpsertCompanyNFeDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompanyNFeDocument,
		arg.RelationID,
		arg.CompanyID,
		arg.NfeDocumentID,
		arg.CompanyRole,
		arg.VisibilityReason,
		arg.FirstSeenNsu,
		arg.LastSeenNsu,
		arg.FirstSyncedAt,
		arg.LastSyncedAt,
	)
	return err
}

const upsertNFeDocument = `-- name: UpsertNFeDocument :one
INSERT INTO nfe_documents (
    id, chave_acesso, modelo, serie, numero, issue_date, competence, authorized_at, protocolo,
    emitente_cnpj, emitente_name, emitente_ie, emitente_uf,
    destinatario_cnpj, destinatario_name, transportador_cnpj, autorizados_cnpj,
    tp_nf, fin_nfe, nat_op, total_value, icms_value, ipi_value,
    situacao, completeness, layout_version, raw_hash, resumo_raw_hash, parse_warnings, tp_amb,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chave_acesso) DO UPDATE SET
    modelo = excluded.modelo,
    serie = excluded.serie,
    numero = excluded.numero,
    issue_date = excluded.issue_date,
    competence = excluded.competence,
    authorized_at = excluded.authorized_at,
    protocolo = excluded.protocolo,
    emitente_cnpj = excluded.emitente_cnpj,
    emitente_name = excluded.emitente_name,
    emitente_ie = excluded.emitente_ie,
    emitente_uf = excluded.emitente_uf,
    destinatario_cnpj = excluded.destinatario_cnpj,
    destinatario_name = excluded.destinatario_name,
    transportador_cnpj = excluded.transportador_cnpj,
    autorizados_cnpj = excluded.autorizados_cnpj,
    tp_nf = excluded.tp_nf,
    fin_nfe = excluded.fin_nfe,
    nat_op = excluded.nat_op,
    total_value = excluded.total_value,
    icms_value = excluded.icms_value,
    ipi_value = excluded.ipi_value,
    situacao = excluded.situacao,
    completeness = excluded.completeness,
    layout_version = excluded.layout_version,
    raw_hash = excluded.raw_hash,
    resumo_raw_hash = excluded.resumo_raw_hash,
    parse_warnings = excluded.parse_warnings,
    tp_amb = excluded.tp_amb,
    updated_at = excluded.updated_at
RETURNING id
`

type UpsertNFeDocumentParams struct {
	ID                string
	ChaveAcesso       string
	Modelo            string
	Serie             string
	Numero            string
	IssueDate         string
	Competence        string
	AuthorizedAt      sql.NullString
	Protocolo         string
	EmitenteCnpj      string
	EmitenteName      string
	EmitenteIe        string
	EmitenteUf        string
	DestinatarioCnpj  string
	DestinatarioName  string
	TransportadorCnpj string
	AutorizadosCnpj   string
	TpNf              string
	FinNfe            string
	NatOp             string
	TotalValue        int64
	IcmsValue         int64
	IpiValue          int64
	Situacao          string
	Completeness      string
	LayoutVersion     string
	RawHash           string
	ResumoRawHash     sql.NullString
	ParseWarnings     sql.NullString
	TpAmb             string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) UpsertNFeDocument(ctx context.Context, arg UpsertNFeDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertNFeDocument,
		arg.ID,
		arg.ChaveAcesso,
		arg.Modelo,
		arg.Serie,
		arg.Numero,
		arg.IssueDate,
		arg.Competence,
		arg.AuthorizedAt,
		arg.Protocolo,
		arg.EmitenteCnpj,
		arg.EmitenteName,
		arg.EmitenteIe,
		arg.EmitenteUf,
		arg.DestinatarioCnpj,
		arg.DestinatarioName,
		arg.TransportadorCnpj,
		arg.AutorizadosCnpj,
		arg.TpNf,
		arg.FinNfe,
		arg.NatOp,
		arg.TotalValue,
		arg.IcmsValue,
		arg.IpiValue,
		arg.Situacao,
		arg.Completeness,
		arg.LayoutVersion,
		arg.RawHash,
		arg.ResumoRawHash,
		arg.ParseWarnings,
		arg.TpAmb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertNFeEvent = `-- name: UpsertNFeEvent :exec
INSERT INTO nfe_events (
    id, nfe_document_id, chave_acesso, tp_evento, type, n_seq_evento, event_at, registered_at,
    registered, c_stat, x_motivo, protocolo, autor_cnpj, description, justificativa, correcao,
    completeness, sent_by_nanci, raw_hash, parse_warnings, tp_amb, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chave_acesso, tp_evento, n_seq_evento) DO UPDATE SET
    nfe_document_id = COALESCE(nfe_events.nfe_document_id, excluded.nfe_document_id),
    type = excluded.type,
    event_at = excluded.event_at,
    registered_at = excluded.registered_at,
    registered = excluded.registered,
    c_stat = excluded.c_stat,
    x_motivo = excluded.x_motivo,
    protocolo = excluded.protocolo,
    autor_cnpj = excluded.autor_cnpj,
    description = excluded.description,
    justificativa = excluded.justificativa,
    correcao = excluded.correcao,
    completeness = excluded.completeness,
    sent_by_nanci = MAX(nfe_events.sent_by_nanci, excluded.sent_by_nanci),
    raw_hash = excluded.raw_hash,
    parse_warnings = excluded.parse_warnings,
    tp_amb = excluded.tp_amb,
    updated_at = excluded.updated_at
WHERE NOT (nfe_events.completeness = 'completa' AND excluded.completeness = 'resumo')
`

type UpsertNFeEventParams struct {
	ID            string
	NfeDocumentID sql.NullString
	ChaveAcesso   string
	TpEvento      string
	Type          string
	NSeqEvento    int64
	EventAt       sql.NullString
	RegisteredAt  sql.NullString
	Registered    int64
	CStat         string
	XMotivo       string
	Protocolo     string
	AutorCnpj     string
	Description   string
	Justificativa string
	Correcao      string
	Completeness  string
	SentByNanci   int64
	RawHash       string
	ParseWarnings sql.NullString
	TpAmb         string
	CreatedAt     string
	UpdatedAt     string
}

// Keeps the row id, created_at, the document link and sent_by_nanci, and
// never lets a resumo overwrite a completa.
func (q *Queries) UpsertNFeEvent(ctx context.Context, arg UpsertNFeEventParams) error {
	_, err := q.db.ExecContext(ctx, upsertNFeEvent,
		arg.ID,
		arg.NfeDocumentID,
		arg.ChaveAcesso,
		arg.TpEvento,
		arg.Type,
		arg.NSeqEvento,
		arg.EventAt,
		arg.RegisteredAt,
		arg.Registered,
		arg.CStat,
		arg.XMotivo,
		arg.Protocolo,
		arg.AutorCnpj,
		arg.Description,
		arg.Justificativa,
		arg.Correcao,
		arg.Completeness,
		arg.SentByNanci,
		arg.RawHash,
		arg.ParseWarnings,
		arg.TpAmb,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
