// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const createSyncRun = `-- name: CreateSyncRun :exec
INSERT INTO sync_runs (
    id, company_id, credential_id, credential_cnpj, consultation_cnpj,
    consultation_basis, started_at, from_nsu, to_nsu, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSyncRunParams struct {
	ID                string
	CompanyID         string
	CredentialID      string
	CredentialCnpj    string
	ConsultationCnpj  string
	ConsultationBasis string
	StartedAt         string
	FromNsu           int64
	ToNsu             int64
	Status            string
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, createSyncRun,
		arg.ID,
		arg.CompanyID,
		arg.CredentialID,
		arg.CredentialCnpj,
		arg.ConsultationCnpj,
		arg.ConsultationBasis,
		arg.StartedAt,
		arg.FromNsu,
		arg.ToNsu,
		arg.Status,
	)
	return err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at = ?, status = ?
WHERE id = ?
`

type FinishSyncRunParams struct {
	FinishedAt sql.NullString
	Status     string
	ID         string
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, finishSyncRun, arg.FinishedAt, arg.Status, arg.ID)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, document_id, chave_acesso, type, event_at, event_at_valid,
    replacement_chave_acesso, description, raw_xml_path, raw_hash,
    parse_warnings, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(raw_hash) DO NOTHING
`

type InsertEventParams struct {
	ID                     string
	DocumentID             sql.NullString
	ChaveAcesso            string
	Type                   string
	EventAt                sql.NullString
	EventAtValid           int64
	ReplacementChaveAcesso string
	Description            string
	RawXmlPath             string
	RawHash                string
	ParseWarnings          sql.NullString
	CreatedAt              string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.DocumentID,
		arg.ChaveAcesso,
		arg.Type,
		arg.EventAt,
		arg.EventAtValid,
		arg.ReplacementChaveAcesso,
		arg.Description,
		arg.RawXmlPath,
		arg.RawHash,
		arg.ParseWarnings,
		arg.CreatedAt,
	)
	return err
}

const listCompanyDocuments = `-- name: ListCompanyDocuments :many
SELECT d.id, d.chave_acesso, d.issue_date, d.competence, d.prestador_cnpj, d.prestador_name, d.tomador_cnpj, d.tomador_name, d.intermediario_cnpj, d.intermediario_name, d.service_value, d.iss_value, d.irrf_value, d.inss_value, d.pis_value, d.cofins_value, d.csll_value, d.total_retentions, d.status, d.layout_version, d.xml_path, d.raw_hash, d.parse_warnings, d.nfse_number, d.service_description, d.created_at, d.updated_at, cd.company_role, cd.visibility_reason 
FROM documents d
JOIN company_documents cd ON d.id = cd.document_id
WHERE cd.company_id = ?
ORDER BY d.issue_date DESC
`

type ListCompanyDocumentsRow struct {
	ID                 string
	ChaveAcesso        string
	IssueDate          string
	Competence         string
	PrestadorCnpj      string
	PrestadorName      string
	TomadorCnpj        string
	TomadorName        string
	IntermediarioCnpj  string
	IntermediarioName  string
	ServiceValue       int64
	IssValue           int64
	IrrfValue          int64
	InssValue          int64
	PisValue           int64
	CofinsValue        int64
	CsllValue          int64
	TotalRetentions    int64
	Status             string
	LayoutVersion      string
	XmlPath            string
	RawHash            string
	ParseWarnings      sql.NullString
	NfseNumber         string
	ServiceDescription string
	CreatedAt          string
	UpdatedAt          string
	CompanyRole        string
	VisibilityReason   string
}

func (q *Queries) ListCompanyDocuments(ctx context.Context, companyID string) ([]ListCompanyDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompanyDocuments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyDocumentsRow
	for rows.Next() {
		var i ListCompanyDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChaveAcesso,
			&i.IssueDate,
			&i.Competence,
			&i.PrestadorCnpj,
			&i.PrestadorName,
			&i.TomadorCnpj,
			&i.TomadorName,
			&i.IntermediarioCnpj,
			&i.IntermediarioName,
			&i.ServiceValue,
			&i.IssValue,
			&i.IrrfValue,
			&i.InssValue,
			&i.PisValue,
			&i.CofinsValue,
			&i.CsllValue,
			&i.TotalRetentions,
			&i.Status,
			&i.LayoutVersion,
			&i.XmlPath,
			&i.RawHash,
			&i.ParseWarnings,
			&i.NfseNumber,
			&i.ServiceDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyRole,
			&i.VisibilityReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRunProgress = `-- name: UpdateSyncRunProgress :exec
UPDATE sync_runs
SET to_nsu = ?, documents_found = ?, errors_count = ?
WHERE id = ?
`

type UpdateSyncRunProgressParams struct {
	ToNsu          int64
	DocumentsFound int64
	ErrorsCount    int64
	ID             string
}

func (q *Queries) UpdateSyncRunProgress(ctx context.Context, arg UpdateSyncRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncRunProgress,
		arg.ToNsu,
		arg.DocumentsFound,
		arg.ErrorsCount,
		arg.ID,
	)
	return err
}

const upsertCompanyDocument = `-- name: UpsertCompanyDocument :exec
INSERT INTO company_documents (
    relation_id, company_id, document_id, company_role, visibility_reason,
    first_seen_nsu, last_seen_nsu, first_seen_nsu_valid, last_seen_nsu_valid,
    first_synced_at, last_synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, document_id) DO UPDATE SET
    last_seen_nsu = excluded.last_seen_nsu,
    last_seen_nsu_valid = excluded.last_seen_nsu_valid,
    last_synced_at = excluded.last_synced_at
`

type UpsertCompanyDocumentParams struct {
	RelationID        string
	CompanyID         string
	DocumentID        string
	CompanyRole       string
	VisibilityReason  string
	FirstSeenNsu      int64
	LastSeenNsu       int64
	FirstSeenNsuValid int64
	LastSeenNsuValid  int64
	FirstSyncedAt     string
	LastSyncedAt      string
}

func (q *Queries) UpsertCompanyDocument(ctx context.Context, arg UpsertCompanyDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompanyDocument,
		arg.RelationID,
		arg.CompanyID,
		arg.DocumentID,
		arg.CompanyRole,
		arg.VisibilityReason,
		arg.FirstSeenNsu,
		arg.LastSeenNsu,
		arg.FirstSeenNsuValid,
		arg.LastSeenNsuValid,
		arg.FirstSyncedAt,
		arg.LastSyncedAt,
	)
	return err
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (
    id, chave_acesso, issue_date, competence,
    prestador_cnpj, prestador_name, tomador_cnpj, tomador_name,
    intermediario_cnpj, intermediario_name,
    service_value, iss_value, irrf_value, inss_value, pis_value, cofins_value, csll_value, total_retentions,
    status, layout_version, xml_path, raw_hash, parse_warnings,
    nfse_number, service_description, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chave_acesso) DO UPDATE SET
    status = excluded.status,
    updated_at = excluded.updated_at
`

type UpsertDocumentParams struct {
	ID                 string
	ChaveAcesso        string
	IssueDate          string
	Competence         string
	PrestadorCnpj      string
	PrestadorName      string
	TomadorCnpj        string
	TomadorName        string
	IntermediarioCnpj  string
	IntermediarioName  string
	ServiceValue       int64
	IssValue           int64
	IrrfValue          int64
	InssValue          int64
	PisValue           int64
	CofinsValue        int64
	CsllValue          int64
	TotalRetentions    int64
	Status             string
	LayoutVersion      string
	XmlPath            string
	RawHash            string
	ParseWarnings      sql.NullString
	NfseNumber         string
	ServiceDescription string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocument,
		arg.ID,
		arg.ChaveAcesso,
		arg.IssueDate,
		arg.Competence,
		arg.PrestadorCnpj,
		arg.PrestadorName,
		arg.TomadorCnpj,
		arg.TomadorName,
		arg.IntermediarioCnpj,
		arg.IntermediarioName,
		arg.ServiceValue,
		arg.IssValue,
		arg.IrrfValue,
		arg.InssValue,
		arg.PisValue,
		arg.CofinsValue,
		arg.CsllValue,
		arg.TotalRetentions,
		arg.Status,
		arg.LayoutVersion,
		arg.XmlPath,
		arg.RawHash,
		arg.ParseWarnings,
		arg.NfseNumber,
		arg.ServiceDescription,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
