// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync.sql

package sqlgen

import (
	"context"
	"database/sql"
)

const createSyncRun = `-- name: CreateSyncRun :exec
INSERT INTO sync_runs (
    id, company_id, credential_id, credential_cnpj, consultation_cnpj,
    consultation_basis, started_at, from_nsu, to_nsu, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSyncRunParams struct {
	ID                string
	CompanyID         string
	CredentialID      string
	CredentialCnpj    string
	ConsultationCnpj  string
	ConsultationBasis string
	StartedAt         string
	FromNsu           int64
	ToNsu             int64
	Status            string
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, createSyncRun,
		arg.ID,
		arg.CompanyID,
		arg.CredentialID,
		arg.CredentialCnpj,
		arg.ConsultationCnpj,
		arg.ConsultationBasis,
		arg.StartedAt,
		arg.FromNsu,
		arg.ToNsu,
		arg.Status,
	)
	return err
}

const finishSyncRun = `-- name: FinishSyncRun :exec
UPDATE sync_runs
SET finished_at = ?, status = ?
WHERE id = ?
`

type FinishSyncRunParams struct {
	FinishedAt sql.NullString
	Status     string
	ID         string
}

func (q *Queries) FinishSyncRun(ctx context.Context, arg FinishSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, finishSyncRun, arg.FinishedAt, arg.Status, arg.ID)
	return err
}

const getDocumentIDByAccessKey = `-- name: GetDocumentIDByAccessKey :one
SELECT id FROM documents WHERE chave_acesso = ? LIMIT 1
`

func (q *Queries) GetDocumentIDByAccessKey(ctx context.Context, chaveAcesso string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDocumentIDByAccessKey, chaveAcesso)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, document_id, chave_acesso, type, event_at, event_at_valid,
    replacement_chave_acesso, description, raw_xml_path, raw_hash,
    parse_warnings, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(raw_hash) DO NOTHING
`

type InsertEventParams struct {
	ID                     string
	DocumentID             sql.NullString
	ChaveAcesso            string
	Type                   string
	EventAt                sql.NullString
	EventAtValid           int64
	ReplacementChaveAcesso string
	Description            string
	RawXmlPath             string
	RawHash                string
	ParseWarnings          sql.NullString
	CreatedAt              string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.DocumentID,
		arg.ChaveAcesso,
		arg.Type,
		arg.EventAt,
		arg.EventAtValid,
		arg.ReplacementChaveAcesso,
		arg.Description,
		arg.RawXmlPath,
		arg.RawHash,
		arg.ParseWarnings,
		arg.CreatedAt,
	)
	return err
}

const linkEventsToDocument = `-- name: LinkEventsToDocument :exec
UPDATE events SET document_id = ? WHERE chave_acesso = ? AND document_id IS NULL
`

type LinkEventsToDocumentParams struct {
	DocumentID  sql.NullString
	ChaveAcesso string
}

func (q *Queries) LinkEventsToDocument(ctx context.Context, arg LinkEventsToDocumentParams) error {
	_, err := q.db.ExecContext(ctx, linkEventsToDocument, arg.DocumentID, arg.ChaveAcesso)
	return err
}

const listEventTypesByAccessKey = `-- name: ListEventTypesByAccessKey :many
SELECT type FROM events WHERE chave_acesso = ?
`

func (q *Queries) ListEventTypesByAccessKey(ctx context.Context, chaveAcesso string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEventTypesByAccessKey, chaveAcesso)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatusByAccessKey = `-- name: UpdateDocumentStatusByAccessKey :exec
UPDATE documents SET status = ?, updated_at = ? WHERE chave_acesso = ?
`

type UpdateDocumentStatusByAccessKeyParams struct {
	Status      string
	UpdatedAt   string
	ChaveAcesso string
}

func (q *Queries) UpdateDocumentStatusByAccessKey(ctx context.Context, arg UpdateDocumentStatusByAccessKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateDocumentStatusByAccessKey, arg.Status, arg.UpdatedAt, arg.ChaveAcesso)
	return err
}

const updateSyncRunProgress = `-- name: UpdateSyncRunProgress :exec
UPDATE sync_runs
SET to_nsu = ?, documents_found = ?, errors_count = ?
WHERE id = ?
`

type UpdateSyncRunProgressParams struct {
	ToNsu          int64
	DocumentsFound int64
	ErrorsCount    int64
	ID             string
}

func (q *Queries) UpdateSyncRunProgress(ctx context.Context, arg UpdateSyncRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncRunProgress,
		arg.ToNsu,
		arg.DocumentsFound,
		arg.ErrorsCount,
		arg.ID,
	)
	return err
}

const upsertCompanyDocument = `-- name: UpsertCompanyDocument :exec
INSERT INTO company_documents (
    relation_id, company_id, document_id, company_role, visibility_reason,
    first_seen_nsu, last_seen_nsu, first_seen_nsu_valid, last_seen_nsu_valid,
    first_synced_at, last_synced_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(company_id, document_id) DO UPDATE SET
    company_role = excluded.company_role,
    visibility_reason = excluded.visibility_reason,
    first_seen_nsu = CASE
        WHEN company_documents.first_seen_nsu_valid = 0 THEN excluded.first_seen_nsu
        WHEN excluded.first_seen_nsu_valid = 0 THEN company_documents.first_seen_nsu
        ELSE MIN(company_documents.first_seen_nsu, excluded.first_seen_nsu)
    END,
    first_seen_nsu_valid = MAX(company_documents.first_seen_nsu_valid, excluded.first_seen_nsu_valid),
    last_seen_nsu = CASE
        WHEN company_documents.last_seen_nsu_valid = 0 THEN excluded.last_seen_nsu
        WHEN excluded.last_seen_nsu_valid = 0 THEN company_documents.last_seen_nsu
        ELSE MAX(company_documents.last_seen_nsu, excluded.last_seen_nsu)
    END,
    last_seen_nsu_valid = MAX(company_documents.last_seen_nsu_valid, excluded.last_seen_nsu_valid),
    last_synced_at = excluded.last_synced_at
`

type UpsertCompanyDocumentParams struct {
	RelationID        string
	CompanyID         string
	DocumentID        string
	CompanyRole       string
	VisibilityReason  string
	FirstSeenNsu      int64
	LastSeenNsu       int64
	FirstSeenNsuValid int64
	LastSeenNsuValid  int64
	FirstSyncedAt     string
	LastSyncedAt      string
}

func (q *Queries) UpsertCompanyDocument(ctx context.Context, arg UpsertCompanyDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertCompanyDocument,
		arg.RelationID,
		arg.CompanyID,
		arg.DocumentID,
		arg.CompanyRole,
		arg.VisibilityReason,
		arg.FirstSeenNsu,
		arg.LastSeenNsu,
		arg.FirstSeenNsuValid,
		arg.LastSeenNsuValid,
		arg.FirstSyncedAt,
		arg.LastSyncedAt,
	)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
    id, chave_acesso, issue_date, competence,
    prestador_cnpj, prestador_name, tomador_cnpj, tomador_name,
    intermediario_cnpj, intermediario_name,
    service_value, iss_value, irrf_value, inss_value, pis_value, cofins_value, csll_value, total_retentions,
    status, layout_version, xml_path, raw_hash, parse_warnings,
    nfse_number, service_description, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(chave_acesso) DO UPDATE SET
    issue_date = excluded.issue_date,
    competence = excluded.competence,
    prestador_cnpj = excluded.prestador_cnpj,
    prestador_name = excluded.prestador_name,
    tomador_cnpj = excluded.tomador_cnpj,
    tomador_name = excluded.tomador_name,
    intermediario_cnpj = excluded.intermediario_cnpj,
    intermediario_name = excluded.intermediario_name,
    service_value = excluded.service_value,
    iss_value = excluded.iss_value,
    irrf_value = excluded.irrf_value,
    inss_value = excluded.inss_value,
    pis_value = excluded.pis_value,
    cofins_value = excluded.cofins_value,
    csll_value = excluded.csll_value,
    total_retentions = excluded.total_retentions,
    status = excluded.status,
    layout_version = excluded.layout_version,
    xml_path = excluded.xml_path,
    raw_hash = excluded.raw_hash,
    parse_warnings = excluded.parse_warnings,
    nfse_number = excluded.nfse_number,
    service_description = excluded.service_description,
    updated_at = excluded.updated_at
RETURNING id
`

type UpsertDocumentParams struct {
	ID                 string
	ChaveAcesso        string
	IssueDate          string
	Competence         string
	PrestadorCnpj      string
	PrestadorName      string
	TomadorCnpj        string
	TomadorName        string
	IntermediarioCnpj  string
	IntermediarioName  string
	ServiceValue       int64
	IssValue           int64
	IrrfValue          int64
	InssValue          int64
	PisValue           int64
	CofinsValue        int64
	CsllValue          int64
	TotalRetentions    int64
	Status             string
	LayoutVersion      string
	XmlPath            string
	RawHash            string
	ParseWarnings      sql.NullString
	NfseNumber         string
	ServiceDescription string
	CreatedAt          string
	UpdatedAt          string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.ID,
		arg.ChaveAcesso,
		arg.IssueDate,
		arg.Competence,
		arg.PrestadorCnpj,
		arg.PrestadorName,
		arg.TomadorCnpj,
		arg.TomadorName,
		arg.IntermediarioCnpj,
		arg.IntermediarioName,
		arg.ServiceValue,
		arg.IssValue,
		arg.IrrfValue,
		arg.InssValue,
		arg.PisValue,
		arg.CofinsValue,
		arg.CsllValue,
		arg.TotalRetentions,
		arg.Status,
		arg.LayoutVersion,
		arg.XmlPath,
		arg.RawHash,
		arg.ParseWarnings,
		arg.NfseNumber,
		arg.ServiceDescription,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
