// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {nfse} from '../models';

export function AddCompany(arg1:app.AddCompanyInput):Promise<void>;

export function CancelCertPassword():Promise<void>;

export function ExportCSV(arg1:app.ExportInput):Promise<void>;

export function ExportXLSX(arg1:app.ExportInput):Promise<void>;

export function ExportZIP(arg1:app.ExportInput):Promise<void>;

export function ListCompanies():Promise<Array<nfse.Company>>;

export function ListDocuments(arg1:app.ListInput):Promise<Array<nfse.Document>>;

export function Pull(arg1:app.PullInput):Promise<app.PullResult>;

export function SelectCertificate():Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function Status(arg1:string):Promise<app.StatusResult>;

export function SubmitCertPassword(arg1:string):Promise<void>;
