// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {desktopapi} from '../models';

export function AddCompany(arg1:app.AddCompanyInput):Promise<void>;

export function AddCredential(arg1:app.AddCredentialInput):Promise<void>;

export function AssignCredentialToCompany(arg1:app.AssignCredentialInput):Promise<void>;

export function CancelCertPassword(arg1:string):Promise<void>;

export function ExportDANFSe(arg1:desktopapi.ExportDANFSeInput):Promise<desktopapi.ExportResult>;

export function ExportDANFSeZIP(arg1:desktopapi.ExportDocumentsInput):Promise<desktopapi.ExportResult>;

export function ExportDocuments(arg1:desktopapi.ExportDocumentsInput):Promise<desktopapi.ExportResult>;

export function ExportLogs():Promise<string>;

export function ListCompanies():Promise<Array<desktopapi.CompanySummary>>;

export function ListCredentials():Promise<Array<desktopapi.CredentialSummary>>;

export function ListDocuments(arg1:app.ListInput):Promise<Array<desktopapi.DocumentRow>>;

export function ListEventsForDocument(arg1:string):Promise<Array<desktopapi.DocumentEvent>>;

export function Pull(arg1:app.PullInput):Promise<app.PullResult>;

export function QueryNFSe(arg1:app.QueryNFSeInput):Promise<string>;

export function QueryNFSeEvents(arg1:app.QueryNFSeInput):Promise<string>;

export function ResetSyncState(arg1:app.ResetSyncInput):Promise<void>;

export function SelectCertificate():Promise<string>;

export function SelectExportDirectory():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetLogLevel(arg1:string):Promise<void>;

export function Status(arg1:string):Promise<app.StatusResult>;

export function SubmitCertPassword(arg1:string,arg2:string):Promise<void>;

export function ToggleDebug(arg1:boolean):Promise<void>;

export function UpdateCompany(arg1:app.UpdateCompanyInput):Promise<void>;

export function UpdateCredentialData(arg1:app.UpdateCredentialDataInput):Promise<void>;

export function UpdateCredentialPath(arg1:app.UpdateCredentialPathInput):Promise<void>;
