// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCompany(arg1) {
  return window['go']['main']['App']['AddCompany'](arg1);
}

export function CancelCertPassword() {
  return window['go']['main']['App']['CancelCertPassword']();
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function ExportXLSX(arg1) {
  return window['go']['main']['App']['ExportXLSX'](arg1);
}

export function ExportZIP(arg1) {
  return window['go']['main']['App']['ExportZIP'](arg1);
}

export function ListCompanies() {
  return window['go']['main']['App']['ListCompanies']();
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function SelectCertificate() {
  return window['go']['main']['App']['SelectCertificate']();
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function SubmitCertPassword(arg1) {
  return window['go']['main']['App']['SubmitCertPassword'](arg1);
}
