// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCompany(arg1) {
  return window['go']['main']['App']['AddCompany'](arg1);
}

export function AddCredential(arg1) {
  return window['go']['main']['App']['AddCredential'](arg1);
}

export function AssignCredentialToCompany(arg1) {
  return window['go']['main']['App']['AssignCredentialToCompany'](arg1);
}

export function CancelCertPassword(arg1) {
  return window['go']['main']['App']['CancelCertPassword'](arg1);
}

export function ExportDANFSe(arg1) {
  return window['go']['main']['App']['ExportDANFSe'](arg1);
}

export function ExportDANFSeZIP(arg1) {
  return window['go']['main']['App']['ExportDANFSeZIP'](arg1);
}

export function ExportDocuments(arg1) {
  return window['go']['main']['App']['ExportDocuments'](arg1);
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function ExportXML(arg1) {
  return window['go']['main']['App']['ExportXML'](arg1);
}

export function ListCompanies() {
  return window['go']['main']['App']['ListCompanies']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListEventsForDocument(arg1) {
  return window['go']['main']['App']['ListEventsForDocument'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function QueryNFSe(arg1) {
  return window['go']['main']['App']['QueryNFSe'](arg1);
}

export function QueryNFSeEvents(arg1) {
  return window['go']['main']['App']['QueryNFSeEvents'](arg1);
}

export function ResetSyncState(arg1) {
  return window['go']['main']['App']['ResetSyncState'](arg1);
}

export function SelectCertificate() {
  return window['go']['main']['App']['SelectCertificate']();
}

export function SelectExportDirectory() {
  return window['go']['main']['App']['SelectExportDirectory']();
}

export function SelectSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function SubmitCertPassword(arg1, arg2) {
  return window['go']['main']['App']['SubmitCertPassword'](arg1, arg2);
}

export function ToggleDebug(arg1) {
  return window['go']['main']['App']['ToggleDebug'](arg1);
}

export function UpdateCompany(arg1) {
  return window['go']['main']['App']['UpdateCompany'](arg1);
}

export function UpdateCredentialData(arg1) {
  return window['go']['main']['App']['UpdateCredentialData'](arg1);
}

export function UpdateCredentialPath(arg1) {
  return window['go']['main']['App']['UpdateCredentialPath'](arg1);
}
